services:
  api_gateway:
    build: ./backend/gateway
    container_name: "gateway"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend/gateway:/backend/gateway
    networks:
      - inventoryApp_network

  api_products:
    build: ./backend/products_mService
    container_name: "api-products"
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./backend/products_mService:/backend/products
    networks:
      - inventoryApp_network
    depends_on:
      - mysql_database

  api_users:
    build: ./backend/users_mService
    container_name: "api-users"
    ports:
      - "8082:8082"
    env_file:
      - .env
    volumes:
      - ./backend/users_mService:/backend/users
    networks:
      - inventoryApp_network
    depends_on:
      - mysql_database

  api_inventories:
    build: ./backend/inventory_mService
    container_name: "api-inventories"
    ports:
      - "8083:8083"
    env_file:
      - .env
    volumes:
      - ./backend/inventory_mService:/backend/inventories
    networks:
      - inventoryApp_network
    depends_on:
      - mysql_database

  mysql_database:
    image: mysql:8.0.42
    container_name: database
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - database_data:/app/data
    networks:
      - inventoryApp_network

networks:
  inventoryApp_network:

volumes:
  database_data:
