spring:
  application:
    name: inventory_app.gateway

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://api-users:8082
          predicates:
            - Path=/account/id/**
            - Path=/account/register
            - Path=/account/add-user
            - Path=/account/delete
            - Path=/logincheck
            - Path=/user/**
          filters:
            - AuthenticationFilter

        - id: inventories-service
          uri: http://api-inventories:8083
          predicates:
            - Path=/graphql
          filters:
            - AuthenticationFilter

        - id: products-service
          uri: http://api-products:8081
          predicates:
            - Path=/product/edit
            - Path=/category/**
          filters:
            - AuthenticationFilter
