server:
  port: 8080

spring:
  application:
    name: inventory_app.gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users-service
              uri: http://api-users:8082
              predicates:
                - Path=/account/id/**,/account/register,/account/add-user,/account/delete,/authenticate/**,/user/**,/e2e/users-service/**
              filters:
                - AuthenticationFilter

            - id: inventories-service
              uri: http://api-inventories:8083
              predicates:
                - Path=/graphql/**
              filters:
                - AuthenticationFilter

            - id: products-service
              uri: http://api-products:8081
              predicates:
                - Path=/product/**,/e2e/products-service/**
              filters:
                - AuthenticationFilter

management:
  endpoints:
    web:
      exposure:
        include: gateway,health